import unittest

from generator.generalised_feedback_shift_registers import MersenneTwister32, MersenneTwister64
from test.generator import tools


class TestGFSR(unittest.TestCase):
    SEQUENCES_PATH = "sequences/generalised_feedback_shift_registers"

    def test_mt32_c_s1(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1"""
        self._test_mt32_file(1, 'mt32-s1.txt')
        self._test_mt32_file(1, 'mt32-s1.txt')

    def test_mt32_c_s123(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 123"""
        self._test_mt32_file(123, 'mt32-s123.txt')

    def test_mt32_c_s1877471023(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1877471023"""
        self._test_mt32_file(1877471023, 'mt32-s1877471023.txt')

    def test_mt32_c_s4294967295(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1877471023"""
        self._test_mt32_file(4294967295, 'mt32-s4294967295.txt')

    def test_mt32_oeis_s5489(self):
        """Test against sequence from The On-Line Encyclopedia of Integer Sequences, seed 5489.
        https://oeis.org/A221557"""
        self._test_mt32_file(5489, 'mt32-s5489.txt')

    def test_mt64_c_s1(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1"""
        self._test_mt64_file(1, 'mt64-s1.txt')

    def test_mt64_c_s123(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 123"""
        self._test_mt64_file(123, 'mt64-s123.txt')

    def test_mt64_c_s1877471023(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1877471023"""

        self._test_mt64_file(6609245288487293937, 'mt64-s6609245288487293937.txt')

    def test_mt64_c_s4294967295(self):
        """Test against sequences pre-generated by the Mersenne Twister C implementation
        with seed 1877471023"""
        self._test_mt64_file(18446744073709551615, 'mt64-s18446744073709551615.txt')

    def test_mt64_oeis_s5489(self):
        """Test against sequence from The On-Line Encyclopedia of Integer Sequences, seed 5489.
        https://oeis.org/A221558"""
        self._test_mt64_file(5489, 'mt64-s5489.txt')

    def _test_mt32_file(self, seed, file):
        self._test_mt_file(MersenneTwister32(seed=seed), file)

    def _test_mt64_file(self, seed, file):
        self._test_mt_file(MersenneTwister64(seed=seed), file)

    def _test_mt_file(self, generator, file):
        generated_sequence, expected_sequence = tools.number_sequences_to_compare(
            generator, self.SEQUENCES_PATH + '/' + file)
        self.assertListEqual(generated_sequence, expected_sequence)


if __name__ == '__main__':
    unittest.main()
